### ISSUE TITLE
libuv doesn't build with gcc3.4

### ISSUE THREAD

**Issue by rmustacc** [joyent/libuv#63]
On GCC 3.4.3 (csl-sol210-3_4-20050802) libuv fails to build:

rm ~/src/libuv $ gmake
gcc --std=gnu89 -Wno-variadic-macros -g -c uv-unix.c -o uv-unix.o
cc1: error: unrecognized command line option "-Wno-variadic-macros"
gmake: **\* [uv-unix.o] Error 1

That warning didn't exist in the GCC 3.4 timeframe. GCC 3.4 support may not be desired, if that is the case it's fine to close the bug and declare it not supported.

**Comment by ry** [comment]
I think we should actually be building with `--ansi --pedantic` unfortunately we're doing a lot of function pointer to `void*` implicit casts in the code right now. `--pedantic` doesn't like that.

**Comment by rmustacc** [comment]
I added in -Wpointer-arith as a test and that didn't actually change anything. The bigger problems are going to be the following errors (gcc 4.3.3 / Linux x86) which are due to libev and c-ares.

~/src/libuv $ gmake
gcc -ansi -pedantic -g -c uv-unix.c -o uv-unix.o
In file included from uv.h:36,
                 from uv-unix.c:21:
c-ares/ares.h:380: error: expected declaration specifiers or ‘...’ before ‘fd_set’
c-ares/ares.h:381: error: expected declaration specifiers or ‘...’ before ‘fd_set’
c-ares/ares.h:392: error: expected declaration specifiers or ‘...’ before ‘fd_set’
c-ares/ares.h:393: error: expected declaration specifiers or ‘...’ before ‘fd_set’
In file included from uv-unix.h:27,
                 from uv.h:54,
                 from uv-unix.c:21:
ev/ev.h:200: warning: ISO C restricts enumerator values to range of ‘int’
ev/ev.h:223: warning: ISO C restricts enumerator values to range of ‘int’
gmake: **\* [uv-unix.o] Error 1

**Comment by bnoordhuis** [comment]
https://github.com/bagder/c-ares/pull/6 <- fixes fd_set issue

**Comment by rmustacc** [comment]
This works now.
