### ISSUE TITLE
windows: build error with MinGW

### ISSUE THREAD

**Issue by starwing** [joyent/libuv#801]
gcc -Ie:/Work/Code/tv_ads/lua/lua-libuv/libuv/include -Ie:/Work/Code/tv_ads/lua/
lua-libuv/libuv/include/uv-private -g --std=gnu89 -D_WIN32_WINNT=0x0600 -Ie:/Wor
k/Code/tv_ads/lua/lua-libuv/libuv/include -Ie:/Work/Code/tv_ads/lua/lua-libuv/li
buv/include/uv-private  -c -o e:/Work/Code/tv_ads/lua/lua-libuv/libuv/src/win/pr
ocess.o e:/Work/Code/tv_ads/lua/lua-libuv/libuv/src/win/process.c
e:/Work/Code/tv_ads/lua/lua-libuv/libuv/src/win/process.c: In function 'uv__init
_global_job_handle':
e:/Work/Code/tv_ads/lua/lua-libuv/libuv/src/win/process.c:61:7: error: 'JOB_OBJE
CT_LIMIT_BREAKAWAY_OK' undeclared (first use in this function)
e:/Work/Code/tv_ads/lua/lua-libuv/libuv/src/win/process.c:61:7: note: each undec
lared identifier is reported only once for each function it appears in
e:/Work/Code/tv_ads/lua/lua-libuv/libuv/src/win/process.c:62:7: error: 'JOB_OBJE
CT_LIMIT_SILENT_BREAKAWAY_OK' undeclared (first use in this function)
e:/Work/Code/tv_ads/lua/lua-libuv/libuv/src/win/process.c:64:7: error: 'JOB_OBJE
CT_LIMIT_KILL_ON_JOB_CLOSE' undeclared (first use in this function)
make: **\* [e:/Work/Code/tv_ads/lua/lua-libuv/libuv/src/win/process.o] Error 1

**Comment by piscisaureus** [comment]
Which version of MinGW is this? And do you happen to know if mingw_w64 also lacks these symbols?

**Comment by starwing** [comment]
this is my MinGW version:

```
C:\Program Files (x86)\Microsoft Visual Studio 10.0\VC>gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=e:/dev/mingw/bin/../libexec/gcc/i686-pc-mingw32/4.7.1/lto-wr
apper.exe
Target: i686-pc-mingw32
Configured with: ../src/configure --prefix=/c/temp/gcc/dest --with-gmp=/c/temp/g
cc/gmp --with-mpfr=/c/temp/gcc/mpfr --with-mpc=/c/temp/gcc/mpc --enable-language
s=c,c++ --with-arch=i686 --with-tune=generic --disable-libstdcxx-pch --disable-n
ls --disable-shared --disable-sjlj-exceptions --disable-win32-registry --enable-
checking=release --enable-lto
Thread model: win32
gcc version 4.7.1 (GCC)
```

it's from [MinGW-distro](http://nuwen.net/mingw.html), I don't know whether MinGW64 is work :(

**Comment by bitraft** [comment]
http://tdm-gcc.tdragon.net/ also has same error.

**Comment by bnoordhuis** [comment]
FWIW, as of commit b1d390e I'm able to cross-compile with the mingw32-gcc 4.7.2 from the FC18 repository. Considered fixed, closing.
