### ISSUE TITLE
Compilation errors

### ISSUE THREAD

**Issue by genisaguilar** [joyent/libuv#1298]
I found some errors when trying to compile with gcc version 4.8.2  on Ubuntu 12.04. Mostly regarding operations between enum types and structs with enum types that were returned by value and but initialized. 

Full diff can be found in: https://gist.github.com/genisaguilar/ef9c4f411dc912bd1cef

After fixing the compilation errors, tests seem to go well.

**Comment by saghul** [comment]
I assume you meant to open this bug in the neovim project, right?

**Comment by genisaguilar** [comment]
Yes sorry, I'll move it there
